dist: trusty
os: windows
language: go

before_install:
- git config --system core.longpaths true
- rd /s amitkrout/wintravistest
- git clone --depth=50 --branch=master https://github.com/amitkrout/wintravistest.git amitkrout/wintravistest

jobs:
  include:
    - &base-test
      stage: test
      go_import_path: github.com/amitkrout/wintravistest
      go: "1.11.2"
      install:
        - make goget-tools
      script:
        - make bin
